# Generated by Django 4.2.3 on 2023-10-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_first_name', models.CharField(max_length=20)),
                ('students_last_name', models.CharField(max_length=20)),
                ('students_address', models.CharField(max_length=20)),
                ('student_mobile', models.CharField(max_length=20)),
                ('students_phy', models.CharField(max_length=20)),
                ('students_chem', models.CharField(max_length=20)),
                ('students_bio', models.CharField(max_length=20)),
                ('students_maths', models.CharField(max_length=20)),
                ('PCB_percentage', models.CharField(max_length=20)),
                ('PCM_percentage', models.CharField(max_length=20)),
            ],
        ),
    ]
